-- MySQL Script generated by MySQL Workbench
-- Tue Apr  5 18:21:14 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cocktails
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cocktails
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cocktails` DEFAULT CHARACTER SET utf8 ;
USE `cocktails` ;

-- -----------------------------------------------------
-- Table `cocktails`.`set_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cocktails`.`set_user` ;

CREATE TABLE IF NOT EXISTS `cocktails`.`set_user` (
  `set_id` CHAR(36) NOT NULL,
  `user_id` CHAR(36) NOT NULL,
  PRIMARY KEY (`set_id`, `user_id`),
  INDEX `fk_set_has_user_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_set_has_user_set1_idx` (`set_id` ASC) VISIBLE,
  CONSTRAINT `fk_set_has_user_set1`
    FOREIGN KEY (`set_id`)
    REFERENCES `cocktails`.`set` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_set_has_user_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `cocktails`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cocktails`.`cocktail_set`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cocktails`.`cocktail_set` ;

CREATE TABLE IF NOT EXISTS `cocktails`.`cocktail_set` (
  `cocktail_id` CHAR(36) NOT NULL,
  `set_id` CHAR(36) NOT NULL,
  INDEX `fk_cocktail_has_set_set1_idx` (`set_id` ASC) VISIBLE,
  INDEX `fk_cocktail_has_set_cocktail1_idx` (`cocktail_id` ASC) VISIBLE,
  PRIMARY KEY (`cocktail_id`, `set_id`),
  CONSTRAINT `fk_cocktail_has_set_cocktail1`
    FOREIGN KEY (`cocktail_id`)
    REFERENCES `cocktails`.`cocktail` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cocktail_has_set_set1`
    FOREIGN KEY (`set_id`)
    REFERENCES `cocktails`.`set` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
