-- MySQL Script generated by MySQL Workbench
-- Thu Feb 17 17:03:08 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cocktails
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cocktails
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cocktails` DEFAULT CHARACTER SET utf8 ;
USE `cocktails` ;

-- -----------------------------------------------------
-- Table `cocktails`.`ingredient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cocktails`.`ingredient` (
  `id` CHAR(36) NOT NULL,
  `alc` INT NULL,
  `unit` TINYTEXT NULL,
  `name_id` CHAR(36) NOT NULL,
  `description_id` CHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ingredient_label1_idx` (`name_id` ASC) VISIBLE,
  INDEX `fk_ingredient_label2_idx` (`description_id` ASC) VISIBLE,
  UNIQUE INDEX `name_id_UNIQUE` (`name_id` ASC) VISIBLE,
  UNIQUE INDEX `description_id_UNIQUE` (`description_id` ASC) VISIBLE,
  CONSTRAINT `fk_ingredient_label1`
    FOREIGN KEY (`name_id`)
    REFERENCES `cocktails`.`label` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ingredient_label2`
    FOREIGN KEY (`description_id`)
    REFERENCES `cocktails`.`label` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cocktails`.`cocktail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cocktails`.`cocktail` (
  `id` CHAR(36) NOT NULL,
  `image` TINYTEXT NULL,
  `name_id` CHAR(36) NOT NULL,
  `description_id` CHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cocktail_label1_idx` (`name_id` ASC) VISIBLE,
  UNIQUE INDEX `name_id_UNIQUE` (`name_id` ASC) VISIBLE,
  INDEX `fk_cocktail_label2_idx` (`description_id` ASC) VISIBLE,
  UNIQUE INDEX `description_id_UNIQUE` (`description_id` ASC) VISIBLE,
  CONSTRAINT `fk_cocktail_label1`
    FOREIGN KEY (`name_id`)
    REFERENCES `cocktails`.`label` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cocktail_label2`
    FOREIGN KEY (`description_id`)
    REFERENCES `cocktails`.`label` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cocktails`.`cocktail_ingredient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cocktails`.`cocktail_ingredient` (
  `cocktail_id` CHAR(36) NOT NULL,
  `ingredient_id` CHAR(36) NOT NULL,
  PRIMARY KEY (`cocktail_id`, `ingredient_id`),
  INDEX `fk_cocktail_has_ingredient_ingredient1_idx` (`ingredient_id` ASC) VISIBLE,
  INDEX `fk_cocktail_has_ingredient_cocktail1_idx` (`cocktail_id` ASC) VISIBLE,
  CONSTRAINT `fk_cocktail_has_ingredient_cocktail1`
    FOREIGN KEY (`cocktail_id`)
    REFERENCES `cocktails`.`cocktail` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cocktail_has_ingredient_ingredient1`
    FOREIGN KEY (`ingredient_id`)
    REFERENCES `cocktails`.`ingredient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
